# Generated by Django 4.2.16 on 2026-02-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_broker_id', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField()),
                ('entry_price', models.FloatField()),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('position_size_usd', models.FloatField()),
                ('capital', models.FloatField()),
                ('leverage', models.FloatField(default=500)),
                ('order_volume', models.FloatField(blank=True, null=True)),
                ('liquidity_price', models.FloatField()),
                ('break_even_price', models.FloatField()),
                ('order_commission', models.FloatField()),
                ('close_time', models.DateTimeField(blank=True, null=True)),
                ('close_price', models.FloatField(blank=True, null=True)),
                ('pnl', models.FloatField(blank=True, null=True)),
                ('pnl_excluding_commission', models.FloatField(blank=True, null=True)),
                ('max_drawdown', models.FloatField(blank=True, null=True)),
                ('max_profit', models.FloatField(blank=True, null=True)),
                ('closing_reason', models.CharField(blank=True, choices=[('TP', 'Take Profit'), ('SL', 'Stop Loss'), ('MANUAL', 'Manual'), ('LIQUIDATION', 'Liquidation'), ('OTHER', 'Other')], max_length=50, null=True)),
                ('is_partially_closed', models.BooleanField(default=False)),
                ('strategy', models.CharField(max_length=50)),
                ('broker', models.CharField(max_length=50)),
                ('market_type', models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Crypto'), ('OTHER', 'Other')], max_length=50)),
                ('timeframe', models.CharField(choices=[('1M', '1 Minute'), ('5M', '5 Minutes'), ('15M', '15 Minutes'), ('1H', '1 Hour'), ('4H', '4 Hours'), ('1D', '1 Day')], max_length=50)),
                ('setup_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeClosePricesMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mutation_time', models.DateTimeField(auto_now_add=True)),
                ('mutation_price', models.FloatField(blank=True, null=True)),
                ('new_tp_price', models.FloatField(blank=True, null=True)),
                ('new_sl_price', models.FloatField(blank=True, null=True)),
                ('pnl_at_new_tp_price', models.FloatField(blank=True, null=True)),
                ('pnl_at_new_sl_price', models.FloatField(blank=True, null=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_prices_mutations', to='nexus.trade')),
            ],
            options={
                'verbose_name': "Trade Close Prices Mutation",
                'verbose_name_plural': "Trade Close Prices Mutations",
                'ordering': ['mutation_time'],
            },
        ),
    ]
