#!/command/with-contenv bash

export WINEARCH=win64
export WINEPREFIX="/config/.wine"
export DISPLAY=:0
export HOME=/config
export XDG_RUNTIME_DIR=/tmp/runtime-abc

echo "Starting MT5 Python API Service..."
exec s6-setuidgid abc wine python -u /app/app.py
